/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fajar.desktop.myagenda.gui;

import com.fajar.desktop.myagenda.Agenda;
import com.fajar.desktop.myagenda.utils.ReportUtil;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.write.WriteException; 

/**
 *
 * @author fajar
 */
public class MyAgenda extends javax.swing.JFrame {

    /**
     * Creates new form AcaraPanitia
     */
    private List<Agenda> agendaList = new ArrayList<>();
    private boolean isAddNew = true;
    private Agenda selectedAgenda = new Agenda();
    private int beginningHour = 0, beginningMinute = 0;
    private int currentHour = 0, currentMinute = 0;
    private Integer durationHour = 0, durationMinute = 0;
    private String path = "";
    DefaultTableModel model;
    
    public MyAgenda() {
        initComponents();
        initBaginningTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxHour = new javax.swing.JComboBox<>();
        comboBoxMinute = new javax.swing.JComboBox<>();
        textBoxDuration = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textBoxAgendaName = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_update_mulai = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        comboBoxPrevious = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        textBoxDurationHour = new javax.swing.JTextField();
        textBoxDurationMinute = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_path = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        agendaTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rundown");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jLabel1.setText("Durasi ");

        jLabel2.setText("Mulai");

        comboBoxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        comboBoxHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHourActionPerformed(evt);
            }
        });

        comboBoxMinute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        comboBoxMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMinuteActionPerformed(evt);
            }
        });

        textBoxDuration.setEnabled(false);
        textBoxDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxDurationActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Kegiatan*");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah Baru");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_update_mulai.setText("Ok");
        btn_update_mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_mulaiActionPerformed(evt);
            }
        });

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboBoxPrevious.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        comboBoxPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPreviousActionPerformed(evt);
            }
        });

        jLabel5.setText("Kegiatan Sebelumnya");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textBoxDurationHour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBoxDurationHourKeyReleased(evt);
            }
        });

        textBoxDurationMinute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textBoxDurationMinuteKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("jam");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("min");

        jButton3.setText("Cetak");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Load Excel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("min");

        jButton5.setText("Pilih File");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("File Path");

        txt_path.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_simpan)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)
                                .addComponent(txt_path, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxHour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textBoxDurationHour, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textBoxDurationMinute, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(comboBoxMinute, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textBoxDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(btn_update_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBoxPrevious, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBoxAgendaName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(comboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_update_mulai))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(textBoxDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textBoxDurationHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textBoxDurationMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(9, 9, 9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(27, 27, 27)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textBoxAgendaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_simpan)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jLabel8)
                    .addComponent(txt_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        agendaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        agendaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(agendaTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Agenda getAgendaById(int id) {
        for (Agenda k : agendaList) {
            if (k.getId() == id) {
                return k;
            }
        }
        return null;
    }
    
    private Agenda getAgendaByName(String nama) {
        for (Agenda k : agendaList) {
            if (k.getAgendaName().equals(nama)) {
                return k;
            }
        }
        return null;
    }

    private void textBoxDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxDurationActionPerformed
       
    }//GEN-LAST:event_textBoxDurationActionPerformed
    
    private Agenda getAgendaByPrevId(int id) {
        for (Agenda k : agendaList) {
            if (k.getPreviousId().equals(id)) {
                return k;
            }
        }
        return null;
    }
    
    private boolean updateAgenda(Agenda agenda) {
        for (Agenda k : agendaList) {
            if (Objects.equals(k.getId(), agenda.getId())) {
                k = agenda;
                return true;
            }
        }
        return false;
    }
    
    private boolean checkNameAvailability(Agenda agenda) {
        for (Agenda k : agendaList) {
            if (k.getAgendaName().equals(agenda.getAgendaName())) {
                if (!k.getId().equals(agenda.getId())) {
                    return false;
                }
            }
        }
        return true;
    }
    
    private void replacePrev(Agenda move, Agenda previousAgenda) {
        
        int idPrevOld = move.getPreviousId();
        Agenda oldPredecessor = getAgendaByPrevId(move.getId());
        System.out.println("MOVE " + move);
        System.out.println("has prev " + previousAgenda);
        System.out.println("OLD SUCCESSOR " + oldPredecessor);
        if (oldPredecessor != null) {
            oldPredecessor.setPreviousId(idPrevOld);
        }
        
        if (previousAgenda != null) {
            move.setPreviousId(previousAgenda.getPreviousId());
            previousAgenda.setPreviousId(move.getId());
            
        }
        
        System.out.println("--new move " + move);
        System.out.println("--new hasprev " + previousAgenda);
        System.out.println("--new oldSuccessor " + oldPredecessor);
        
        for (Agenda k : agendaList) {
            if (k.getId().equals(move.getId())) {
                k = move;
            } else if (previousAgenda != null && k.getId().equals(previousAgenda.getId())) {
                k = previousAgenda;
            } else if (oldPredecessor != null && k.getId().equals(oldPredecessor.getId())) {
                k = oldPredecessor;
            }
        }
        
    }

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
       
        Random r = new Random();
        int newAgendaId = 1000 + r.nextInt(9000);
        if (isAddNew) {
            selectedAgenda.setId(newAgendaId);
        }
        int durasi = Integer.parseInt(textBoxDuration.getText());
        String agendaName = textBoxAgendaName.getText();
        Agenda prev = getAgendaByName(comboBoxPrevious.getSelectedItem().toString());
        if (prev != null && prev.getId().equals(selectedAgenda.getId())) {
            JOptionPane.showMessageDialog(null, "Pilih kegiatan lain");
            return;
        }
        int idPrev = prev == null ? 0 : prev.getId();
        Agenda hasPrev = getAgendaByPrevId(idPrev);
        
        if (hasPrev != null && selectedAgenda.getPreviousId() != idPrev) {
            replacePrev(selectedAgenda, hasPrev);
        } else if (hasPrev == null && getAgendaByPrevId(selectedAgenda.getId()) != null) {
            replacePrev(selectedAgenda, hasPrev);
        }
        
        if (isAddNew) {
            selectedAgenda = new Agenda(newAgendaId, durasi, agendaName);
            selectedAgenda.setPreviousId(idPrev);
            if (idPrev == 0 && getAgendaByPrevId(0) != null) {
                replacePrev(selectedAgenda, getAgendaByPrevId(0));
            }
            if (!checkNameAvailability(selectedAgenda)) {
                JOptionPane.showConfirmDialog(null, "Nama tidak boleh sama !");
                return;
            }
            agendaList.add(selectedAgenda);
        } else {
            selectedAgenda.setDuration(durasi);
            selectedAgenda.setAgendaName(agendaName);
            selectedAgenda.setPreviousId(idPrev);
            if (!checkNameAvailability(selectedAgenda)) {
                JOptionPane.showConfirmDialog(null, "Nama tidak boleh sama !");
                return;
            }
            updateAgenda(selectedAgenda);
            isAddNew = true;
        }
        resetField();
        updateTabel(agendaList);

    }//GEN-LAST:event_btn_simpanActionPerformed
    
    private void resetField() {
        textBoxDurationHour.setText("0");
        textBoxDurationMinute.setText("0");
        textBoxDuration.setText("0");
        durationHour = 0;
        durationMinute = 0;
        textBoxAgendaName.setText("");
        selectedAgenda = new Agenda();
    }

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
       
        isAddNew = true;
        resetField();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void agendaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendaTableMouseClicked
       
        int row = agendaTable.getSelectedRow();
        int id = Integer.parseInt(agendaTable.getModel().getValueAt(row, 1).toString());
        selectedAgenda = getAgendaById(id);
        if (selectedAgenda != null) {
            isAddNew = false;
            durationHour = selectedAgenda.getDuration() / 60;
            durationMinute = selectedAgenda.getDuration() % 60;
            textBoxDurationHour.setText(durationHour.toString());
            textBoxDurationMinute.setText(durationMinute.toString());
            textBoxDuration.setText(selectedAgenda.getDuration().toString());
            textBoxAgendaName.setText(selectedAgenda.getAgendaName());
            int idPrev = selectedAgenda.getPreviousId();
            
            Agenda prev = idPrev != 0 ? getAgendaById(idPrev) : null;
            System.out.println(selectedAgenda + " prev= " + prev);
            comboBoxPrevious.setSelectedItem(selectedAgenda.getPreviousId() != 0 ? prev.getAgendaName() : "none");
        }
    }//GEN-LAST:event_agendaTableMouseClicked

    private void comboBoxHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHourActionPerformed
       
        beginningHour = Integer.parseInt(comboBoxHour.getSelectedItem().toString());
    }//GEN-LAST:event_comboBoxHourActionPerformed

    private void comboBoxMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMinuteActionPerformed
       
        beginningMinute = Integer.parseInt(comboBoxMinute.getSelectedItem().toString());
    }//GEN-LAST:event_comboBoxMinuteActionPerformed

    private void btn_update_mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_mulaiActionPerformed
       
        updateTabel(agendaList);
    }//GEN-LAST:event_btn_update_mulaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        deleteAgenda(selectedAgenda);
        updateTabel(agendaList);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        agendaList.clear();
        updateTabel(agendaList);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void updateDur() {
        Integer min_dur = durationHour * 60 + durationMinute;
        textBoxDuration.setText(min_dur.toString());
    }

    private void textBoxDurationHourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBoxDurationHourKeyReleased
       
        String dur = textBoxDurationHour.getText();
        durationHour = dur.equals("") ? 0 : Integer.parseInt(dur);
        updateDur();
    }//GEN-LAST:event_textBoxDurationHourKeyReleased

    private void textBoxDurationMinuteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBoxDurationMinuteKeyReleased
       
        String dur = textBoxDurationMinute.getText();
        durationMinute = dur.equals("") ? 0 : Integer.parseInt(dur);
        updateDur();
    }//GEN-LAST:event_textBoxDurationMinuteKeyReleased

    private void comboBoxPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPreviousActionPerformed
       
    }//GEN-LAST:event_comboBoxPreviousActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
           
            ReportUtil.printReport(agendaTable);
        } catch (WriteException ex) {
            Logger.getLogger(MyAgenda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MyAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        List<Agenda> ls = ReportUtil.loadAgenda(path);
        if (ls.size() > 0) {
            agendaList = ls;
            updateTabel(agendaList);
        }else{
            JOptionPane.showMessageDialog(null, "FILE TIDAK VALID");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        JFileChooser fc = new JFileChooser();
        FileFilter ff_xls = new FileNameExtensionFilter("xls", "xls");
        FileFilter ff_xlsx = new FileNameExtensionFilter("xlsx", "xlsx");
        fc.addChoosableFileFilter(ff_xls);
        fc.addChoosableFileFilter(ff_xlsx);
        int result = fc.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            path = fc.getSelectedFile().getAbsolutePath();
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Cancel was selected");
        }
        txt_path.setText(path);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAgenda().setVisible(true);
            }
        });
        
    }
    
    private void updateComboBox(List<Agenda> agendas) {
        comboBoxPrevious.removeAllItems();
        comboBoxPrevious.addItem("none");
        for (Agenda k : agendas) {
            comboBoxPrevious.addItem(k.getAgendaName());
            
        }
    }
    
    private void updateHour(int duration) {
        int hour = currentHour;
        int minute = currentMinute;
        for (int i = 1; i <= duration; i++) {
            minute++;
            // System.out.println("menit " + menit);
            if (minute % 60 == 0) {
                hour++;
                if (hour > 23) {
                    hour = 0;
                }
                minute = 0;
            }
        }
        
        currentHour = hour;
        currentMinute = minute;
    }
    
    private void deleteAgenda(Agenda kg) {
        Agenda kAfter = getAgendaByPrevId(kg.getId());
        kAfter.setPreviousId(kg.getPreviousId());
        for (Agenda k : agendaList) {
            if (k.getId().equals(kg.getId())) {
                agendaList.remove(k);
                break;
            }
        }
        for (Agenda k : agendaList) {
            if (k.getId().equals(kAfter.getId())) {
                k = kAfter;
            }
        }
    }
    
    private void updateTabel(List<Agenda> listKegiatan) {
        for (Agenda k : listKegiatan) {
            System.out.println(k);
        }
        System.out.println("---------tabel---------");
        model = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "No", "Id", "Mulai", "Durasi(Menit)", "Selesai", "Nama", "Prev"
                }
        );
        int no = 0;
        currentHour = beginningHour;
        currentMinute = beginningMinute;
        Agenda kRunning = new Agenda();
        for (int i = 0; i < listKegiatan.size(); i++) {
            System.out.print("i " + i + ". ");
            if (i == 0) {
                kRunning = getAgendaByPrevId(0);
            } else {
                int idPrev = kRunning.getId();
                kRunning = getAgendaByPrevId(idPrev);
            }
            System.out.println(kRunning);
            
            Object[] o = new Object[8];
            no++;
            o[0] = no;
            o[1] = kRunning.getId();
            o[2] = currentHour + ":" + currentMinute;
            int durasi = kRunning.getDuration();
            o[3] = durasi;
            updateHour(durasi);
            o[4] = currentHour + ":" + currentMinute;
            o[5] = kRunning.getAgendaName();
            Agenda prev = getAgendaById(kRunning.getPreviousId());
            
            o[6] = kRunning.getPreviousId() != 0 ? prev.getAgendaName() : "-";
            
            model.addRow(o);
            // System.out.println(o);
        }
        agendaTable.setModel(model);
        updateComboBox(listKegiatan);
    }
    
     
     
     
    private void initBaginningTime() {
        for (Integer i = 1; i <= 23; i++) {
            comboBoxHour.addItem(i.toString());
        }
        for (Integer i = 1; i <= 59; i++) {
            comboBoxMinute.addItem(i.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable agendaTable;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update_mulai;
    private javax.swing.JComboBox<String> comboBoxHour;
    private javax.swing.JComboBox<String> comboBoxMinute;
    private javax.swing.JComboBox<String> comboBoxPrevious;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textBoxAgendaName;
    private javax.swing.JTextField textBoxDuration;
    private javax.swing.JTextField textBoxDurationHour;
    private javax.swing.JTextField textBoxDurationMinute;
    private javax.swing.JTextField txt_path;
    // End of variables declaration//GEN-END:variables
}
